$${\bf Name}:\text{  Mainak Biswas}$$

$$ \text {IISc, PhD student, PMRF Lecture (Assignment 2)} $$

In [ ]:
# importing relevant packages
import numpy as np
import sympy

$\bf Note:$ It was mentioned in class that we should use a inbuilt function to find the row reduced Echelon form, and do the rest from scratch. Using sympy.rref() to find the row reduced echelon form of the matrix

In [ ]:
#4 fundamental subspace calculator class
class subspace_calculator(object):
    def __init__(self, m):
        self.A = m
        self.m = m.shape[0]
        self.n = m.shape[1]
        self.dim_col_space = -1
        self.dim_row_space = -1
        self.rank = -1

    def get_matrix(self):
        return self.A

    def get_rref(self, m):
        #convert to row reduced echelon form
        rref_mat = sympy.Matrix(m)
        rref_mat = rref_mat.rref()
        #this returns the echelon form and pivot columns
        rref_mat = np.array(rref_mat[0]).astype(np.float64)
        return rref_mat


    def get_row_space_basis(self):
        #get the row reduced echelon form of A
        rref_A = self.get_rref(self.A)
        #get the first row where all the entries are 0 [U | 0].T: this will give me the number of independent rows of A
        #see each row of A
        stop_idx = self.m
        for i in range(self.m):
            #see if all the entries of the row is 0
            if np.isclose(np.sum(np.abs(rref_A[i, :])), 0):
                stop_idx = i
                break
        #return the basis of the column space and the dimension of the column space
        if stop_idx > 0:
            return rref_A[0:stop_idx, :].T, stop_idx
        else:
            return np.array([[]]), 0

    def get_left_null_space_basis(self):
        #to get the null space of A.T (we can do row reduction for the augmented matrix and take the last m-r rows of it)
        #logic PA = [U|0].T; PI = P => P[A | I] = [[U| 0].T | P], hence the last m-r rows of the augmented side gives us the basis for N(A.T)
        augmented_A = np.concatenate([self.A, np.identity(self.m)], axis=1)
        rref_augmented_A = self.get_rref(augmented_A)
        #return the last m-r rows of the rref form
        if self.m - self.rank > 0:
            return rref_augmented_A[self.rank:,self.n:].T, self.m - self.rank
        else:
            return np.array([[]]), 0

    def get_col_space_basis(self):
        #get the row reduced echelon form of A.T
        rref_A_T = self.get_rref((self.A).T)
        #get the first row where all the entries are 0 [U | 0].T: this will give me the number of basic columns of A (independent rows of A.T)
        #see each row of A.T
        stop_idx = self.n
        for i in range(self.n):
            #see if all the entries of the row is 0
            if np.isclose(np.sum(np.abs(rref_A_T[i, :])), 0):
                stop_idx = i
                break
        #return the basis of the column space and the dimension of the column space
        if stop_idx > 0:
            self.col_space_dim = stop_idx
            self.row_space_dim = stop_idx
            self.rank = stop_idx
            return rref_A_T[0:stop_idx, :].T, stop_idx
        else:
            self.col_space_dim = 0
            self.row_space_dim = 0
            self.rank = 0
            return np.array([[]]), 0

    def get_null_space_basis(self):
        #to get the null space of A (we can do row reduction for the augmented matrix of A.T and take the last n-r rows of it)
        #logic PA.T = [U|0].T; PI = P => P[A.T | I] = [[U| 0].T | P], hence the last n-r rows of the augmented side gives us the basis for N(A.T)
        augmented_A = np.concatenate([self.A.T, np.identity(self.n)], axis=1)
        rref_augmented_A = self.get_rref(augmented_A)
        #return the last m-r rows of the rref form
        if self.m - self.rank > 0:
            return rref_augmented_A[self.rank:,self.m:].T, self.n - self.rank
        else:
            return np.array([[]]), 0

    def print_matrix_subspace_details(self):
        #call this function as it fill details required my null space methods
        basis_c_space, dim_c = self.get_col_space_basis()
        basis_n_space, dim_n = self.get_null_space_basis()
        basis_r_space, dim_r = self.get_row_space_basis()
        basis_ln_space, dim_ln = self.get_left_null_space_basis()

        print("Original Matrix: \n {}\n",self.get_matrix())
        print("Row reduced Echelon form of the A: \n {}\n",self.get_rref(self.A))
        print("Row reduced Echelon form of the A.T: \n {}\n",self.get_rref(self.A.T))



        print("Please note that the basis matrix of each of spaces are formed by stacking the basis vectors as column vectors! Each column in the matrix is a basis vector")
        print("\n Dimension of column space (subspace of R^{}): {} \n Basis(column space): \n {}\n".format(self.m, dim_c, basis_c_space))
        print("\n Dimension of null space (subspace of R^{}): {} \n Basis (null space): \n{}\n".format(self.n, dim_n, basis_n_space))
        print("\n Dimension of row space (subspace of R^{}): {} \n Basis (row space): \n{}\n".format(self.n, dim_r, basis_r_space))
        print("\n Dimension of left null space (subspace of R^{}): {} \n Basis (left null space): \n{}\n".format(self.m, dim_ln, basis_ln_space))

In [ ]:
#Example 1
M = np.array([[1, 2, 0, 2, 1], [3, 6, 1, 9, 6], [2, 4, 1, 7, 5]])
mat_util_tool = subspace_calculator(M)
mat_util_tool.print_matrix_subspace_details()

Original Matrix: 
 {}
 [[1 2 0 2 1]
 [3 6 1 9 6]
 [2 4 1 7 5]]
Row reduced Echelon form of the A: 
 {}
 [[1. 2. 0. 2. 1.]
 [0. 0. 1. 3. 3.]
 [0. 0. 0. 0. 0.]]
Row reduced Echelon form of the A.T: 
 {}
 [[ 1.  0. -1.]
 [ 0.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Please note that the basis matrix of each of spaces are formed by stacking the basis vectors as column vectors! Each column in the matrix is a basis vector

 Dimension of column space (subspace of R^3): 2 
 Basis(column space): 
 [[ 1.  0.]
 [ 0.  1.]
 [-1.  1.]]


 Dimension of null space (subspace of R^5): 3 
 Basis (null space): 
[[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.          1.        ]
 [-1.         -2.          0.33333333]
 [ 1.          2.         -0.66666667]]


 Dimension of row space (subspace of R^5): 2 
 Basis (row space): 
[[1. 0.]
 [2. 0.]
 [0. 1.]
 [2. 3.]
 [1. 3.]]


 Dimension of left null space (subspace of R^3): 1 
 Basis (left null spac

In [ ]:
#example 2:
M2 = np.array([[1, 2, 0, 2, 1]])
mat_util_tool2 = subspace_calculator(M2)
mat_util_tool2.print_matrix_subspace_details()

Original Matrix: 
 {}
 [[1 2 0 2 1]]
Row reduced Echelon form of the A: 
 {}
 [[1. 2. 0. 2. 1.]]
Row reduced Echelon form of the A.T: 
 {}
 [[1.]
 [0.]
 [0.]
 [0.]
 [0.]]
Please note that the basis matrix of each of spaces are formed by stacking the basis vectors as column vectors! Each column in the matrix is a basis vector

 Dimension of column space (subspace of R^1): 1 
 Basis(column space): 
 [[1.]]


 Dimension of null space (subspace of R^5): 0 
 Basis (null space): 
[]


 Dimension of row space (subspace of R^5): 1 
 Basis (row space): 
[[1.]
 [2.]
 [0.]
 [2.]
 [1.]]


 Dimension of left null space (subspace of R^1): 0 
 Basis (left null space): 
[]



In [ ]:
#example 3:
M3 = np.zeros((3,3))
mat_util_tool3 = subspace_calculator(M3)
mat_util_tool3.print_matrix_subspace_details()

Original Matrix: 
 {}
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Row reduced Echelon form of the A: 
 {}
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Row reduced Echelon form of the A.T: 
 {}
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Please note that the basis matrix of each of spaces are formed by stacking the basis vectors as column vectors! Each column in the matrix is a basis vector

 Dimension of column space (subspace of R^3): 0 
 Basis(column space): 
 []


 Dimension of null space (subspace of R^3): 3 
 Basis (null space): 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 Dimension of row space (subspace of R^3): 0 
 Basis (row space): 
[]


 Dimension of left null space (subspace of R^3): 3 
 Basis (left null space): 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [ ]:
#Example 4
M4 = np.array([[1, 2, 2, 3], [2, 4, 1, 3], [3, 6, 1, 4]])
mat_util_tool4 = subspace_calculator(M4)
mat_util_tool4.print_matrix_subspace_details()

Original Matrix: 
 {}
 [[1 2 2 3]
 [2 4 1 3]
 [3 6 1 4]]
Row reduced Echelon form of the A: 
 {}
 [[1. 2. 0. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 0.]]
Row reduced Echelon form of the A.T: 
 {}
 [[ 1.          0.         -0.33333333]
 [ 0.          1.          1.66666667]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
Please note that the basis matrix of each of spaces are formed by stacking the basis vectors as column vectors! Each column in the matrix is a basis vector

 Dimension of column space (subspace of R^3): 2 
 Basis(column space): 
 [[ 1.          0.        ]
 [ 0.          1.        ]
 [-0.33333333  1.66666667]]


 Dimension of null space (subspace of R^4): 2 
 Basis (null space): 
[[ 1.  0.]
 [ 0.  1.]
 [ 1.  2.]
 [-1. -2.]]


 Dimension of row space (subspace of R^4): 2 
 Basis (row space): 
[[1. 0.]
 [2. 0.]
 [0. 1.]
 [1. 1.]]


 Dimension of left null space (subspace of R^3): 1 
 Basis (left null space): 
[[ 1.]
 [-5.]
 [ 3.]]



In [ ]:
#Example 5
M5 = np.array([[1, 1, 3, 3], [1, 2, 3, 3], [1, 1, 3, 3]])
mat_util_tool5 = subspace_calculator(M5)
mat_util_tool5.print_matrix_subspace_details()

Original Matrix: 
 {}
 [[1 1 3 3]
 [1 2 3 3]
 [1 1 3 3]]
Row reduced Echelon form of the A: 
 {}
 [[1. 0. 3. 3.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
Row reduced Echelon form of the A.T: 
 {}
 [[1. 0. 1.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Please note that the basis matrix of each of spaces are formed by stacking the basis vectors as column vectors! Each column in the matrix is a basis vector

 Dimension of column space (subspace of R^3): 2 
 Basis(column space): 
 [[1. 0.]
 [0. 1.]
 [1. 0.]]


 Dimension of null space (subspace of R^4): 2 
 Basis (null space): 
[[ 1.          0.        ]
 [ 0.          0.        ]
 [ 0.          1.        ]
 [-0.33333333 -1.        ]]


 Dimension of row space (subspace of R^4): 2 
 Basis (row space): 
[[1. 0.]
 [0. 1.]
 [3. 0.]
 [3. 0.]]


 Dimension of left null space (subspace of R^3): 1 
 Basis (left null space): 
[[ 1.]
 [ 0.]
 [-1.]]

